import { TerrainPreset } from "../types";

export const PRESETS: TerrainPreset[] = [
  {
    id: "fuji",
    name: "Mount Fuji",
    region: "Honshu, Japan",
    description: "Iconic stratovolcano with symmetrical conical slopes, summit crater, and distinct alpine snowline.",
    center: { lat: 35.3606, lng: 138.7274 },
    bbox: {
      north: 35.405,
      south: 35.315,
      east: 138.785,
      west: 138.67,
    },
    defaultHeightScale: 1.5,
    streetView: {
      lat: 35.3622,
      lng: 138.7314,
      heading: 180,
      pitch: 10,
    },
  },
  {
    id: "grand-canyon",
    name: "Grand Canyon (Mather Point)",
    region: "Arizona, USA",
    description: "Extravagant carved sedimentary cliffs, steep talus slopes, and plateau buttes along the Colorado River.",
    center: { lat: 36.0573, lng: -112.1437 },
    bbox: {
      north: 36.10,
      south: 36.01,
      east: -112.08,
      west: -112.20,
    },
    defaultHeightScale: 2.0,
    streetView: {
      lat: 36.0597,
      lng: -112.1091,
      heading: 350,
      pitch: -15,
    },
  },
  {
    id: "yosemite",
    name: "Yosemite Valley & Half Dome",
    region: "California, USA",
    description: "Sheer vertical granite monoliths, glacial U-shaped valley floor, and steep mountain gullies.",
    center: { lat: 37.7459, lng: -119.5332 },
    bbox: {
      north: 37.78,
      south: 37.71,
      east: -119.48,
      west: -119.59,
    },
    defaultHeightScale: 1.8,
    streetView: {
      lat: 37.7456,
      lng: -119.534,
      heading: 65,
      pitch: 25,
    },
  },
  {
    id: "matterhorn",
    name: "The Matterhorn",
    region: "Zermatt, Switzerland / Italy",
    description: "Pyramidal peak with jagged ridges, steep arêtes, and glacial cirques in the Pennine Alps.",
    center: { lat: 45.9763, lng: 7.6586 },
    bbox: {
      north: 46.01,
      south: 45.94,
      east: 7.71,
      west: 7.61,
    },
    defaultHeightScale: 1.6,
    streetView: {
      lat: 45.9765,
      lng: 7.6582,
      heading: 0,
      pitch: 30,
    },
  },
  {
    id: "rainier",
    name: "Mount Rainier",
    region: "Washington, USA",
    description: "Glacier-clad massive stratovolcano towering above river valleys in the Cascade Range.",
    center: { lat: 46.8523, lng: -121.7603 },
    bbox: {
      north: 46.90,
      south: 46.80,
      east: -121.68,
      west: -121.84,
    },
    defaultHeightScale: 1.6,
    streetView: {
      lat: 46.8523,
      lng: -121.7603,
      heading: 200,
      pitch: 15,
    },
  },
  {
    id: "san-francisco",
    name: "San Francisco Twin Peaks & Bay",
    region: "California, USA",
    description: "Urban rolling hill topography surrounded by ocean and bay coastal shorelines.",
    center: { lat: 37.7544, lng: -122.4477 },
    bbox: {
      north: 37.78,
      south: 37.72,
      east: -122.40,
      west: -122.48,
    },
    defaultHeightScale: 2.2,
    streetView: {
      lat: 37.7544,
      lng: -122.4477,
      heading: 45,
      pitch: -10,
    },
  },
];
